apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  image:
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/imported-from: docker.io/ljhiyh/chat-server:v2
    labels:
      app: chat-server
      version: v2
    name: chat-server:v2
  tag:
    from:
      kind: DockerImage
      name: docker.io/ljhiyh/chat-server:v2
    generation: 2
    importPolicy: {}
    name: v2
    referencePolicy:
      type: Source
kind: List
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: chat-server
    version: v2
  name: chat-server-v2
spec:
  replicas: 1
  selector:
    app: chat-server
    deploymentconfig: chat-server
    version: v2
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
      labels:
        app: chat-server
        deploymentconfig: chat-server
        version: v2
    spec:
      containers:
      - image: docker.io/ljhiyh/chat-server:v2
        imagePullPolicy: IfNotPresent
        name: chat-server
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chat-server
      from:
        kind: ImageStreamTag
        name: chat-server:v2
      lastTriggeredImage: docker.io/ljhiyh/chat-server:v2
    type: ImageChange

