apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  image:
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/imported-from: docker.io/ljhiyh/chat-client:apple
    labels:
      app: chat-client
      version: apple
    name: chat-client:apple
  tag:
    from:
      kind: DockerImage
      name: docker.io/ljhiyh/chat-client:apple
    generation: 2
    importPolicy: {}
    name: apple
    referencePolicy:
      type: Source
kind: List
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: chat-client
    version: apple
  name: chat-client-apple
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: chat-client
    deploymentconfig: chat-client-apple
    version: apple
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: chat-client
        deploymentconfig: chat-client-apple
        version: apple
    spec:
      containers:
      - image: docker.io/ljhiyh/chat-client:apple
        imagePullPolicy: IfNotPresent
        name: chat-client
        ports:
        - containerPort: 4200
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4200
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chat-client
      from:
        kind: ImageStreamTag
        name: chat-client:apple
    type: ImageChange

