apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: details
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: details
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
      - name: details
        image: ljhiyh/auth
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

